#!/bin/bash

# Potions Theme Generator — per-tool adapters (Phase 1)
# Each adapter reads the resolved token variables (COLOR_*/COMPONENT_*, set by
# theme_resolve) and writes ONE generated artifact that its tool includes.
# Adapters never read .theme files directly — they consume the already-validated
# token environment, so untrusted input never reaches them.
#
# Generated artifacts live under gitignored locations and are regenerable; they
# are the persistence contract. OSC live-repaint (shell adapter) is additive.

# Guard against multiple inclusion
if [ -n "${THEME_ADAPTERS_SOURCED:-}" ]; then
  return 0
fi
THEME_ADAPTERS_SOURCED=1

# --- token accessors (indirect expansion; keys are literals in adapter code) --
_thx() { local k="${1}_HEX"; printf '%s' "${!k}"; }
_tct() { local k="${1}_CTERM"; printf '%s' "${!k}"; }

_theme_potions_home() { echo "${POTIONS_HOME:-$HOME/.potions}"; }

_theme_write_atomic() {
  # _theme_write_atomic <dest> < content-on-stdin
  local dest="$1" dir tmp
  dir="$(dirname "$dest")"
  [ -d "$dir" ] || mkdir -p "$dir"
  tmp="$dest.tmp.$$"
  cat > "$tmp"
  if [ -f "$dest" ]; then
    cmp -s "$tmp" "$dest" && { rm -f "$tmp"; return 0; }  # unchanged: skip
    cp "$dest" "$dest.bak" 2>/dev/null || true
  fi
  mv "$tmp" "$dest"
}

# --- Shell ANSI map + OSC live-repaint -------------------------------------
# Writes config/generated/ansi-map.sh: a POSIX function that repaints the live
# terminal palette (OSC 4/10/11) plus POTIONS_COLOR_* hex exports for prompts.
theme_gen_adapter_shell() {
  local home dest
  home="$(_theme_potions_home)"
  dest="$home/config/generated/ansi-map.sh"

  # ANSI slot -> token (consistent across variants)
  local s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 sfg sbg
  s0="$(_thx COLOR_SURFACE_DEEP)";  s1="$(_thx COLOR_ERROR)"
  s2="$(_thx COLOR_ACCENT_NATURE)"; s3="$(_thx COLOR_ACCENT_WARM)"
  s4="$(_thx COLOR_ACCENT_COOL)";   s5="$(_thx COLOR_PRIMARY)"
  s6="$(_thx COLOR_PRIMARY_DEEP)";  s7="$(_thx COLOR_MUTED)"
  s8="$(_thx COLOR_MUTED)";         s9="$(_thx COLOR_ERROR)"
  s10="$(_thx COLOR_ACCENT_NATURE)"; s11="$(_thx COLOR_ACCENT_WARM)"
  s12="$(_thx COLOR_ACCENT_COOL)";  s13="$(_thx COLOR_PRIMARY_MID)"
  s14="$(_thx COLOR_PRIMARY)";      s15="$(_thx COLOR_ON_SURFACE)"
  sfg="$(_thx COLOR_ON_SURFACE)";   sbg="$(_thx COLOR_SURFACE)"

  _theme_write_atomic "$dest" <<EOF
#!/bin/sh
# Generated by the Potions theme generator — DO NOT EDIT.
# Sourced by .zshrc. Repaints the live terminal palette via OSC and exports
# the active palette as POTIONS_COLOR_* for prompts/scripts.

# Repaint the running terminal's ANSI palette to the active theme.
# Best-effort: skips non-interactive, capability-poor, and in-multiplexer cases
# (inside Zellij the generated Zellij theme owns the palette).
potions_apply_terminal_palette() {
  [ -t 1 ] || return 0
  [ -n "\${ZELLIJ:-}" ] && return 0
  case "\${TERM:-}" in dumb|linux|'') return 0 ;; esac
  printf '\033]10;%s\007' '$sfg'
  printf '\033]11;%s\007' '$sbg'
  printf '\033]4;0;%s\007'  '$s0'
  printf '\033]4;1;%s\007'  '$s1'
  printf '\033]4;2;%s\007'  '$s2'
  printf '\033]4;3;%s\007'  '$s3'
  printf '\033]4;4;%s\007'  '$s4'
  printf '\033]4;5;%s\007'  '$s5'
  printf '\033]4;6;%s\007'  '$s6'
  printf '\033]4;7;%s\007'  '$s7'
  printf '\033]4;8;%s\007'  '$s8'
  printf '\033]4;9;%s\007'  '$s9'
  printf '\033]4;10;%s\007' '$s10'
  printf '\033]4;11;%s\007' '$s11'
  printf '\033]4;12;%s\007' '$s12'
  printf '\033]4;13;%s\007' '$s13'
  printf '\033]4;14;%s\007' '$s14'
  printf '\033]4;15;%s\007' '$s15'
}

POTIONS_COLOR_PRIMARY='$(_thx COLOR_PRIMARY)'
POTIONS_COLOR_PRIMARY_DEEP='$(_thx COLOR_PRIMARY_DEEP)'
POTIONS_COLOR_SURFACE='$sbg'
POTIONS_COLOR_ON_SURFACE='$sfg'
POTIONS_COLOR_ERROR='$(_thx COLOR_ERROR)'
export POTIONS_COLOR_PRIMARY POTIONS_COLOR_PRIMARY_DEEP POTIONS_COLOR_SURFACE POTIONS_COLOR_ON_SURFACE POTIONS_COLOR_ERROR
EOF
}

# --- Zellij theme ----------------------------------------------------------
# Writes <config-dir>/themes/potions-active.kdl. config.kdl sets theme
# "potions-active". Zellij is launched with --config-dir "$POTIONS_HOME/zellij".
theme_gen_adapter_zellij() {
  local home dest
  home="$(_theme_potions_home)"
  dest="$home/zellij/themes/potions-active.kdl"

  _theme_write_atomic "$dest" <<EOF
// Generated by the Potions theme generator — DO NOT EDIT.
// Active Alchemist's Orchid variant. Switch with: potions theme set <variant>
themes {
    potions-active {
        fg "$(_thx COLOR_ON_SURFACE)"
        bg "$(_thx COLOR_SURFACE)"
        black "$(_thx COLOR_SURFACE_DEEP)"
        red "$(_thx COLOR_ERROR)"
        green "$(_thx COLOR_ACCENT_NATURE)"
        yellow "$(_thx COLOR_ACCENT_WARM)"
        blue "$(_thx COLOR_ACCENT_COOL)"
        magenta "$(_thx COLOR_PRIMARY)"
        cyan "$(_thx COLOR_PRIMARY_DEEP)"
        white "$(_thx COLOR_MUTED)"
        orange "$(_thx COLOR_PRIMARY_MID)"
    }
}
EOF
}

# --- NeoVim palette --------------------------------------------------------
# Writes nvim/generated/palette.vim: variant colorscheme + barbar/Visual/cheat
# highlight overrides. gui* colors come from tokens; cterm* keeps the named
# 8/16-color fallbacks so non-truecolor terminals (Termux) stay legible.
theme_gen_adapter_nvim() {
  local home dest variant cs
  home="$(_theme_potions_home)"
  dest="$home/nvim/generated/palette.vim"
  variant="${META_VARIANT:-dark}"

  if [ "$variant" = "white" ]; then
    cs="alchemists-orchid-light"
  else
    cs="alchemists-orchid"
  fi

  _theme_write_atomic "$dest" <<EOF
" Generated by the Potions theme generator — DO NOT EDIT.
" Sourced by init.vim. Switch with: potions theme set <variant>

lua << LUA
local ok = pcall(vim.cmd, 'colorscheme $cs')
if not ok then pcall(vim.cmd, 'colorscheme alchemists-orchid') end
LUA

function! s:PotionsThemeHighlights() abort
  highlight Visual              guifg=$(_thx COMPONENT_NVIM_FG_BRIGHT) guibg=$(_thx COMPONENT_NVIM_VISUAL) ctermfg=White ctermbg=DarkGrey
  highlight BufferCurrent       guifg=$(_thx COMPONENT_NVIM_FG_BRIGHT) guibg=$(_thx COMPONENT_NVIM_TAB_ACTIVE) gui=bold ctermfg=White        ctermbg=DarkGrey cterm=bold
  highlight BufferCurrentMod    guifg=$(_thx COLOR_ACCENT_WARM)        guibg=$(_thx COMPONENT_NVIM_TAB_ACTIVE) gui=bold ctermfg=LightMagenta ctermbg=DarkGrey cterm=bold
  highlight BufferCurrentIndex  guifg=$(_thx COLOR_PRIMARY)            guibg=$(_thx COMPONENT_NVIM_TAB_ACTIVE) gui=bold ctermfg=Magenta      ctermbg=DarkGrey cterm=bold
  highlight BufferCurrentSign   guifg=$(_thx COLOR_ACCENT_WARM)        guibg=$(_thx COMPONENT_NVIM_TAB_ACTIVE) gui=bold ctermfg=LightMagenta ctermbg=DarkGrey cterm=bold
  highlight BufferVisible       guifg=$(_thx COMPONENT_NVIM_FG_DIM)    guibg=$(_thx COMPONENT_NVIM_TAB_VISIBLE) ctermfg=Gray    ctermbg=Black
  highlight BufferVisibleMod    guifg=$(_thx COLOR_ACCENT_WARM)        guibg=$(_thx COMPONENT_NVIM_TAB_VISIBLE) ctermfg=Magenta ctermbg=Black
  highlight BufferVisibleIndex  guifg=$(_thx COMPONENT_NVIM_MUTED)     guibg=$(_thx COMPONENT_NVIM_TAB_VISIBLE) ctermfg=DarkGray ctermbg=Black
  highlight BufferVisibleSign   guifg=$(_thx COMPONENT_NVIM_MUTED)     guibg=$(_thx COMPONENT_NVIM_TAB_VISIBLE) ctermfg=DarkGray ctermbg=Black
  highlight BufferInactive      guifg=$(_thx COMPONENT_NVIM_FG_DIM)    guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=Gray    ctermbg=Black
  highlight BufferInactiveMod   guifg=$(_thx COLOR_ACCENT_WARM)        guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=Magenta ctermbg=Black
  highlight BufferInactiveIndex guifg=$(_thx COMPONENT_NVIM_MUTED)     guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=DarkGray ctermbg=Black
  highlight BufferInactiveSign  guifg=$(_thx COMPONENT_NVIM_MUTED)     guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=DarkGray ctermbg=Black
  highlight BufferTabpageFill   guifg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=Black ctermbg=Black
  highlight PotionsCheatNormal  guifg=$(_thx COLOR_SECONDARY)          guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=White        ctermbg=Black
  highlight PotionsCheatBorder  guifg=$(_thx COLOR_PRIMARY)            guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) ctermfg=Magenta      ctermbg=Black
  highlight PotionsCheatTitle   guifg=$(_thx COLOR_ACCENT_WARM)        guibg=$(_thx COMPONENT_NVIM_TAB_INACTIVE) gui=bold ctermfg=LightMagenta ctermbg=Black cterm=bold
endfunction

augroup PotionsThemeHighlights
  autocmd!
  autocmd ColorScheme * call s:PotionsThemeHighlights()
augroup END
call s:PotionsThemeHighlights()
EOF
}

# --- Terminal emulator color file (Alacritty TOML) -------------------------
# Writes config/generated/alacritty-colors.toml; alacritty.toml imports it.
theme_gen_adapter_terminal() {
  local home dest
  home="$(_theme_potions_home)"
  dest="$home/config/generated/alacritty-colors.toml"

  _theme_write_atomic "$dest" <<EOF
# Generated by the Potions theme generator — DO NOT EDIT.
# Imported by alacritty.toml. Switch with: potions theme set <variant>
[colors.primary]
foreground = "$(_thx COLOR_ON_SURFACE)"
background = "$(_thx COLOR_SURFACE)"

[colors.normal]
black   = "$(_thx COLOR_SURFACE_DEEP)"
red     = "$(_thx COLOR_ERROR)"
green   = "$(_thx COLOR_ACCENT_NATURE)"
yellow  = "$(_thx COLOR_ACCENT_WARM)"
blue    = "$(_thx COLOR_ACCENT_COOL)"
magenta = "$(_thx COLOR_PRIMARY)"
cyan    = "$(_thx COLOR_PRIMARY_DEEP)"
white   = "$(_thx COLOR_MUTED)"

[colors.bright]
black   = "$(_thx COLOR_MUTED)"
red     = "$(_thx COLOR_ERROR)"
green   = "$(_thx COLOR_ACCENT_NATURE)"
yellow  = "$(_thx COLOR_ACCENT_WARM)"
blue    = "$(_thx COLOR_ACCENT_COOL)"
magenta = "$(_thx COLOR_PRIMARY_MID)"
cyan    = "$(_thx COLOR_PRIMARY)"
white   = "$(_thx COLOR_ON_SURFACE)"
EOF
}
