#!/bin/bash

# Potions Theme Generator (C2) — Phase 0 skeleton
# Compiles the active theme into generated artifacts that tools include.
#
# Phase 0 establishes the resolve -> emit pipeline and emits ONE consolidated
# artifact: the resolved active-theme environment (resolved.env), a flat
# sourceable KEY=value snapshot of every resolved token. This is exactly what
# the shell-ANSI adapter will source. Phase 1 adds the per-tool adapters
# (zellij theme block, nvim palette, terminal color file) over this same pipe.
#
# Generated output is written under a gitignored directory and is therefore
# never tracked and never checksummed.

# Guard against multiple inclusion
if [ -n "${THEME_GENERATOR_SOURCED:-}" ]; then
  return 0
fi
THEME_GENERATOR_SOURCED=1

_THEME_GEN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -z "${THEME_RESOLVER_SOURCED:-}" ]; then
  # shellcheck source=/dev/null
  . "$_THEME_GEN_DIR/resolver.sh"
fi
if [ -z "${THEME_ADAPTERS_SOURCED:-}" ]; then
  # shellcheck source=/dev/null
  . "$_THEME_GEN_DIR/adapters.sh"
fi

# Per-tool adapter targets (theme_gen_adapter_<target> defined in adapters.sh).
# The termux adapter self-gates to a no-op off-Termux.
THEME_GENERATOR_TARGETS="shell zellij nvim terminal termux"

# Default location for generated artifacts (gitignored, regenerable).
theme_generator_out_dir() {
  echo "${THEME_GENERATOR_OUT_DIR:-${POTIONS_HOME:-$HOME/.potions}/config/generated}"
}

# Emit the resolved environment snapshot (the shared adapter input).
# Usage: theme_generator_emit_env <out_dir>
theme_generator_emit_env() {
  local out_dir="$1" out key seen=" "
  out="$out_dir/resolved.env"

  {
    printf '# Generated by the Potions theme generator — DO NOT EDIT.\n'
    printf '# Resolved active theme palette. Regenerate via: potions theme set <variant>\n\n'
    for key in $THEME_RESOLVED_KEYS; do
      case "$seen" in
        *" $key "*) continue ;;  # de-duplicate (variant overrides base)
      esac
      seen="$seen$key "
      printf '%s=%s\n' "$key" "${!key}"
    done
  } > "$out"
}

# Generate all artifacts for a resolved theme variant.
# Usage: theme_generate <theme_dir> <variant> [out_dir]
theme_generate() {
  local theme_dir="$1" variant="$2"
  local out_dir="${3:-$(theme_generator_out_dir)}"
  local target

  theme_resolve "$theme_dir" "$variant" || return 1

  [ -d "$out_dir" ] || mkdir -p "$out_dir"
  theme_generator_emit_env "$out_dir"

  # Phase 1: dispatch to per-tool adapters reading the resolved env.
  for target in $THEME_GENERATOR_TARGETS; do
    if command -v "theme_gen_adapter_$target" > /dev/null 2>&1; then
      "theme_gen_adapter_$target" "$out_dir" || return 1
    fi
  done

  return 0
}
