#!/bin/bash

# Potions Plugin Lockfile Management
# Handles Potionfile.lock creation, reading, and verification

# Guard against multiple inclusion
if [ -n "$LOCKFILE_SOURCED" ]; then
  return 0
fi
export LOCKFILE_SOURCED=1

# Source core accessories if not already sourced
CORE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$(dirname "$CORE_DIR")"
REPO_ROOT="$(dirname "$PLUGINS_DIR")"

if [ -z "$ACCESSORIES_SOURCED" ]; then
  source "$REPO_ROOT/packages/accessories.sh"
fi

# Lockfile location
LOCKFILE_PATH="${POTIONS_HOME}/Potionfile.lock"
LOCKFILE_HEADER="# Potionfile.lock - Auto-generated by Potions
# DO NOT EDIT MANUALLY
# Format: name|version|checksum|source
#
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
"

# Initialize lockfile if it doesn't exist
# Usage: lockfile_init
lockfile_init() {
  if [ ! -f "$LOCKFILE_PATH" ]; then
    ensure_directory "$(dirname "$LOCKFILE_PATH")"
    echo "$LOCKFILE_HEADER" > "$LOCKFILE_PATH"
    log "Created lockfile at: $LOCKFILE_PATH"
  fi
}

# Read entire lockfile
# Usage: lockfile_read
lockfile_read() {
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 1
  fi
  
  # Return non-comment, non-empty lines
  grep -v '^#' "$LOCKFILE_PATH" | grep -v '^$'
}

# Check if plugin is in lockfile
# Usage: lockfile_has <plugin_name>
lockfile_has() {
  local plugin_name="$1"
  
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 1
  fi
  
  grep -q "^${plugin_name}|" "$LOCKFILE_PATH"
}

# Get plugin entry from lockfile
# Usage: lockfile_get <plugin_name>
# Returns: name|version|checksum|source
lockfile_get() {
  local plugin_name="$1"
  
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 1
  fi
  
  grep "^${plugin_name}|" "$LOCKFILE_PATH" | head -1
}

# Get specific field from lockfile entry
# Usage: lockfile_get_field <plugin_name> <field_number>
# Fields: 1=name, 2=version, 3=checksum, 4=source
lockfile_get_field() {
  local plugin_name="$1"
  local field_num="$2"
  
  local entry
  entry=$(lockfile_get "$plugin_name")
  
  if [ -z "$entry" ]; then
    return 1
  fi
  
  echo "$entry" | cut -d'|' -f"$field_num"
}

# Get plugin version from lockfile
# Usage: lockfile_get_version <plugin_name>
lockfile_get_version() {
  lockfile_get_field "$1" 2
}

# Get plugin checksum from lockfile
# Usage: lockfile_get_checksum <plugin_name>
lockfile_get_checksum() {
  lockfile_get_field "$1" 3
}

# Get plugin source from lockfile
# Usage: lockfile_get_source <plugin_name>
lockfile_get_source() {
  lockfile_get_field "$1" 4
}

# Add plugin to lockfile
# Usage: lockfile_add <name> <version> <checksum> <source>
lockfile_add() {
  local name="$1"
  local version="$2"
  local checksum="${3:-none}"
  local source="$4"
  
  lockfile_init
  
  # Remove existing entry if present
  if lockfile_has "$name"; then
    lockfile_remove "$name"
  fi
  
  # Add new entry
  echo "${name}|${version}|${checksum}|${source}" >> "$LOCKFILE_PATH"
  log "Added to lockfile: $name v$version"
}

# Remove plugin from lockfile
# Usage: lockfile_remove <plugin_name>
lockfile_remove() {
  local plugin_name="$1"
  
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 1
  fi
  
  if ! lockfile_has "$plugin_name"; then
    log "Plugin not found in lockfile: $plugin_name"
    return 1
  fi
  
  # Create temp file without the plugin entry
  local temp_file
  temp_file=$(mktemp)
  grep -v "^${plugin_name}|" "$LOCKFILE_PATH" > "$temp_file"
  mv "$temp_file" "$LOCKFILE_PATH"
  
  log "Removed from lockfile: $plugin_name"
}

# Update plugin in lockfile
# Usage: lockfile_update <name> <version> <checksum> <source>
lockfile_update() {
  local name="$1"
  local version="$2"
  local checksum="${3:-none}"
  local source="$4"
  
  lockfile_remove "$name" 2>/dev/null
  lockfile_add "$name" "$version" "$checksum" "$source"
}

# List all plugins in lockfile
# Usage: lockfile_list
lockfile_list() {
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 0
  fi
  
  lockfile_read | cut -d'|' -f1
}

# Count plugins in lockfile
# Usage: lockfile_count
lockfile_count() {
  if [ ! -f "$LOCKFILE_PATH" ]; then
    echo "0"
    return 0
  fi
  
  lockfile_read | wc -l | tr -d ' '
}

# Verify installed plugins match lockfile
# Usage: lockfile_verify
lockfile_verify() {
  local errors=0
  local plugins_dir="$POTIONS_HOME/plugins"
  
  if [ ! -f "$LOCKFILE_PATH" ]; then
    log "No lockfile found"
    return 1
  fi
  
  while IFS='|' read -r name version checksum source; do
    [ -z "$name" ] && continue
    
    local plugin_path="$plugins_dir/$name"
    
    # Check if plugin directory exists
    if [ ! -d "$plugin_path" ]; then
      log "Missing plugin: $name (expected at $plugin_path)"
      errors=$((errors + 1))
      continue
    fi
    
    # Check version matches (if not local)
    if [ "$source" != "local" ]; then
      local installed_version
      installed_version=$(get_plugin_version "$plugin_path" 2>/dev/null)
      
      if [ "$installed_version" != "$version" ]; then
        log "Version mismatch for $name: expected $version, found $installed_version"
        errors=$((errors + 1))
      fi
    fi
    
    # Verify checksum if present
    if [ "$checksum" != "none" ] && [ "$checksum" != "local" ]; then
      # Checksum verification would go here
      # For now, just check that the manifest exists
      if [ ! -f "$plugin_path/plugin.potions.json" ]; then
        log "Missing manifest for: $name"
        errors=$((errors + 1))
      fi
    fi
    
  done < <(lockfile_read)
  
  if [ $errors -gt 0 ]; then
    log "Lockfile verification failed with $errors error(s)"
    return 1
  fi
  
  log "Lockfile verification passed"
  return 0
}

# Generate lockfile from currently installed plugins
# Usage: lockfile_regenerate
lockfile_regenerate() {
  local plugins_dir="$POTIONS_HOME/plugins"
  local temp_file
  temp_file=$(mktemp)
  
  echo "$LOCKFILE_HEADER" > "$temp_file"
  
  if [ ! -d "$plugins_dir" ]; then
    log "No plugins directory found"
    mv "$temp_file" "$LOCKFILE_PATH"
    return 0
  fi
  
  for plugin_path in "$plugins_dir"/*/; do
    [ -d "$plugin_path" ] || continue
    
    local plugin_name
    plugin_name=$(basename "$plugin_path")
    
    # Skip if no manifest
    if [ ! -f "$plugin_path/plugin.potions.json" ]; then
      continue
    fi
    
    local version source checksum
    version=$(get_plugin_version "$plugin_path" 2>/dev/null || echo "unknown")
    
    # Determine source type
    if [ -L "$plugin_path" ]; then
      source="local:$(readlink "$plugin_path")"
      checksum="none"
    else
      source="unknown"
      checksum="none"
    fi
    
    echo "${plugin_name}|${version}|${checksum}|${source}" >> "$temp_file"
  done
  
  mv "$temp_file" "$LOCKFILE_PATH"
  log "Lockfile regenerated"
}

# Display lockfile contents in readable format
# Usage: lockfile_display
lockfile_display() {
  if [ ! -f "$LOCKFILE_PATH" ]; then
    echo "No lockfile found"
    return 1
  fi
  
  echo "Installed Plugins (from lockfile):"
  echo "=================================="
  
  while IFS='|' read -r name version checksum source; do
    [ -z "$name" ] && continue
    printf "%-25s %-10s %s\n" "$name" "v$version" "($source)"
  done < <(lockfile_read)
}

# Clean orphaned entries from lockfile
# Usage: lockfile_clean
lockfile_clean() {
  local plugins_dir="$POTIONS_HOME/plugins"
  local removed=0
  
  if [ ! -f "$LOCKFILE_PATH" ]; then
    return 0
  fi
  
  for name in $(lockfile_list); do
    if [ ! -d "$plugins_dir/$name" ]; then
      lockfile_remove "$name"
      removed=$((removed + 1))
    fi
  done
  
  if [ $removed -gt 0 ]; then
    log "Cleaned $removed orphaned entries from lockfile"
  fi
}
