#!/bin/bash

# compile-themes.sh - Potions theme compiler (C0)
# Author: Henrique A. Lavezzo (Rynaro)
#
# Compiles authored DTCG token sources (*.tokens.json) into the flat
# KEY=value *.theme runtime format consumed by the Potions theme system.
#
# This is a BUILD-TIME / CI-DEV tool only. It requires `jq` and is never
# run on user installs or Termux — users receive the committed *.theme files.
# After editing any *.tokens.json, run this and commit the regenerated *.theme.
#
# Usage:
#   scripts/compile-themes.sh                 # compile every built-in theme
#   scripts/compile-themes.sh <theme-dir>     # compile one theme directory
#   scripts/compile-themes.sh --check         # compile to temp + diff (CI drift gate)

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
THEMES_ROOT="$REPO_ROOT/.potions/themes"

CHECK_MODE=false

log() { echo "compile-themes: $1" >&2; }

require_jq() {
  if ! command -v jq > /dev/null 2>&1; then
    log "ERROR: jq is required (build-time dependency). Install jq and retry."
    exit 1
  fi
}

# Emit the flat .theme content for one *.tokens.json to stdout.
# Usage: compile_one <tokens.json>
compile_one() {
  local json="$1"

  printf '# Generated by scripts/compile-themes.sh — DO NOT EDIT.\n'
  printf '# Source: %s\n' "$(basename "$json")"
  printf '# Edit the .tokens.json source and recompile.\n\n'

  # Metadata block (omit absent keys; schemaVersion defaults to 1)
  jq -r '
    .meta // {} |
    [ if .id      then "META_ID=\(.id)"           else empty end,
      if .name    then "META_NAME=\(.name)"       else empty end,
      if .author  then "META_AUTHOR=\(.author)"   else empty end,
      if .variant then "META_VARIANT=\(.variant)" else empty end,
      if (.variants and (.variants | length > 0))
                  then "META_VARIANTS=\(.variants | join(","))" else empty end,
      if .base    then "META_BASE=\(.base)"       else empty end,
      "META_SCHEMA_VERSION=\(.schemaVersion // 1)"
    ] | .[]
  ' "$json"

  # Semantic color tokens -> COLOR_<NAME>_HEX / _CTERM
  printf '\n'
  jq -r '
    def slug: ascii_upcase | gsub("[.\\-]"; "_");
    (.color // {}) | to_entries[] |
    "COLOR_\(.key | slug)_HEX=\(.value["$value"])\nCOLOR_\(.key | slug)_CTERM=\(.value.cterm)"
  ' "$json"

  # Component-layer tokens -> COMPONENT_<TARGET>_<SLOT>_HEX / _CTERM (optional)
  if jq -e '.component and (.component | length > 0)' "$json" > /dev/null 2>&1; then
    printf '\n'
    jq -r '
      def slug: ascii_upcase | gsub("[.\\-]"; "_");
      (.component // {}) | to_entries[] |
      "COMPONENT_\(.key | slug)_HEX=\(.value["$value"])\nCOMPONENT_\(.key | slug)_CTERM=\(.value.cterm)"
    ' "$json"
  fi
}

# Compile every *.tokens.json inside a theme directory to sibling *.theme files.
# Usage: compile_theme_dir <dir>
compile_theme_dir() {
  local dir="$1"
  local json base out rc=0

  for json in "$dir"/*.tokens.json; do
    [ -f "$json" ] || continue
    base="$(basename "$json" .tokens.json)"
    out="$dir/$base.theme"

    if [ "$CHECK_MODE" = true ]; then
      local tmp
      tmp="$(mktemp)"
      compile_one "$json" > "$tmp"
      if [ -f "$out" ] && diff -q "$out" "$tmp" > /dev/null 2>&1; then
        log "ok (in sync): $out"
      else
        log "DRIFT: $out is out of date — run scripts/compile-themes.sh"
        diff "$out" "$tmp" >&2 || true
        rc=1
      fi
      rm -f "$tmp"
    else
      compile_one "$json" > "$out"
      log "compiled: $out"
    fi
  done

  return $rc
}

# Emit a markdown token table for one *.tokens.json (section header + tables).
docs_section() {
  local json="$1" label
  label="$(jq -r '.meta.variant // "base (shared across variants)"' "$json")"

  printf '### %s\n\n' "$label"
  printf '| Token | Hex | cterm |\n|-------|-----|-------|\n'
  jq -r '
    (.color // {}) | to_entries[] |
    "| `color.\(.key)` | `\(.value["$value"])` | `\(.value.cterm)` |"
  ' "$json"
  if jq -e '.component and (.component | length > 0)' "$json" > /dev/null 2>&1; then
    jq -r '
      (.component // {}) | to_entries[] |
      "| `component.\(.key)` | `\(.value["$value"])` | `\(.value.cterm)` |"
    ' "$json"
  fi
  printf '\n'
}

# Regenerate docs/color-palette.md from the token sources.
generate_docs() {
  local doc="$REPO_ROOT/docs/color-palette.md"
  local dir id json

  {
    printf '# Alchemist'\''s Orchid — Potions Color Palette\n\n'
    printf '<!-- GENERATED by scripts/compile-themes.sh --docs from .potions/themes/*/*.tokens.json.\n'
    printf '     DO NOT EDIT. Edit the .tokens.json sources and run: scripts/compile-themes.sh --docs -->\n\n'
    printf '**Source of truth:** `.potions/themes/<id>/*.tokens.json` (W3C DTCG), compiled to the\n'
    printf 'flat `*.theme` runtime format consumed by the Potions theme generator.\n\n'
    printf '**Switch the active theme:**\n\n'
    printf '```sh\n'
    printf 'potions theme list                          # see installed themes\n'
    printf 'potions theme set alchemists-orchid white   # switch theme/variant\n'
    printf 'potions theme cycle                         # next variant\n'
    printf '```\n\n'

    for dir in "$THEMES_ROOT"/*/; do
      [ -d "$dir" ] || continue
      [ -f "${dir}manifest" ] || continue
      id="$(basename "${dir%/}")"
      printf '## %s\n\n' "$id"
      # base first, then variant files in sorted order
      for json in "${dir}base.tokens.json"; do
        [ -f "$json" ] && docs_section "$json"
      done
      for json in "$dir"*.tokens.json; do
        [ -f "$json" ] || continue
        case "$(basename "$json")" in base.tokens.json) continue ;; esac
        docs_section "$json"
      done
    done

    printf '## ANSI slot mapping\n\n'
    printf 'Every terminal surface (Ghostty, Termux, Alacritty, Kitty, WezTerm), the\n'
    printf 'Zellij theme, and the shell OSC repaint read the **explicit** `color.ansi-0..15`\n'
    printf 'tokens, so the 16-color palette is byte-faithful to the active variant:\n\n'
    printf '| ANSI slot | Token |\n|-----------|-------|\n'
    printf '| `foreground` | `color.on-surface` |\n'
    printf '| `background` | `color.surface` |\n'
    printf '| `cursor` | `color.cursor` |\n'
    printf '| `cursor-text` | `color.cursor-text` |\n'
    printf '| `selection-bg` | `color.selection-bg` |\n'
    printf '| `selection-fg` | `color.selection-fg` |\n'
    printf '| `color0`..`color15` | `color.ansi-0`..`color.ansi-15` |\n\n'
    printf 'The semantic tokens (`color.primary`, `color.accent-*`, `color.error`, the\n'
    printf '`component.nvim.*` shades) drive UI chrome — the NeoVim overrides, Zellij\n'
    printf '`fg`/`bg`, and the `POTIONS_COLOR_*` prompt exports — and are tuned to the\n'
    printf 'same hue family as the ANSI palette.\n'
  } > "$doc"

  log "regenerated: $doc"
}

main() {
  require_jq

  local target=""
  case "${1:-}" in
    --check) CHECK_MODE=true ;;
    --docs)  generate_docs; return $? ;;
    "") ;;
    *) target="$1" ;;
  esac

  local rc=0
  if [ -n "$target" ]; then
    compile_theme_dir "$target" || rc=$?
  else
    local dir
    for dir in "$THEMES_ROOT"/*/; do
      [ -d "$dir" ] || continue
      compile_theme_dir "${dir%/}" || rc=$?
    done
  fi

  return $rc
}

main "$@"
