#!/bin/bash

# compile-themes.sh - Potions theme compiler (C0)
# Author: Henrique A. Lavezzo (Rynaro)
#
# Compiles authored DTCG token sources (*.tokens.json) into the flat
# KEY=value *.theme runtime format consumed by the Potions theme system.
#
# This is a BUILD-TIME / CI-DEV tool only. It requires `jq` and is never
# run on user installs or Termux — users receive the committed *.theme files.
# After editing any *.tokens.json, run this and commit the regenerated *.theme.
#
# Usage:
#   scripts/compile-themes.sh                 # compile every built-in theme
#   scripts/compile-themes.sh <theme-dir>     # compile one theme directory
#   scripts/compile-themes.sh --check         # compile to temp + diff (CI drift gate)

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
THEMES_ROOT="$REPO_ROOT/.potions/themes"

CHECK_MODE=false

log() { echo "compile-themes: $1" >&2; }

require_jq() {
  if ! command -v jq > /dev/null 2>&1; then
    log "ERROR: jq is required (build-time dependency). Install jq and retry."
    exit 1
  fi
}

# Emit the flat .theme content for one *.tokens.json to stdout.
# Usage: compile_one <tokens.json>
compile_one() {
  local json="$1"

  printf '# Generated by scripts/compile-themes.sh — DO NOT EDIT.\n'
  printf '# Source: %s\n' "$(basename "$json")"
  printf '# Edit the .tokens.json source and recompile.\n\n'

  # Metadata block (omit absent keys; schemaVersion defaults to 1)
  jq -r '
    .meta // {} |
    [ if .id      then "META_ID=\(.id)"           else empty end,
      if .name    then "META_NAME=\(.name)"       else empty end,
      if .author  then "META_AUTHOR=\(.author)"   else empty end,
      if .variant then "META_VARIANT=\(.variant)" else empty end,
      if (.variants and (.variants | length > 0))
                  then "META_VARIANTS=\(.variants | join(","))" else empty end,
      if .base    then "META_BASE=\(.base)"       else empty end,
      "META_SCHEMA_VERSION=\(.schemaVersion // 1)"
    ] | .[]
  ' "$json"

  # Semantic color tokens -> COLOR_<NAME>_HEX / _CTERM
  printf '\n'
  jq -r '
    def slug: ascii_upcase | gsub("[.\\-]"; "_");
    (.color // {}) | to_entries[] |
    "COLOR_\(.key | slug)_HEX=\(.value["$value"])\nCOLOR_\(.key | slug)_CTERM=\(.value.cterm)"
  ' "$json"

  # Component-layer tokens -> COMPONENT_<TARGET>_<SLOT>_HEX / _CTERM (optional)
  if jq -e '.component and (.component | length > 0)' "$json" > /dev/null 2>&1; then
    printf '\n'
    jq -r '
      def slug: ascii_upcase | gsub("[.\\-]"; "_");
      (.component // {}) | to_entries[] |
      "COMPONENT_\(.key | slug)_HEX=\(.value["$value"])\nCOMPONENT_\(.key | slug)_CTERM=\(.value.cterm)"
    ' "$json"
  fi
}

# Compile every *.tokens.json inside a theme directory to sibling *.theme files.
# Usage: compile_theme_dir <dir>
compile_theme_dir() {
  local dir="$1"
  local json base out rc=0

  for json in "$dir"/*.tokens.json; do
    [ -f "$json" ] || continue
    base="$(basename "$json" .tokens.json)"
    out="$dir/$base.theme"

    if [ "$CHECK_MODE" = true ]; then
      local tmp
      tmp="$(mktemp)"
      compile_one "$json" > "$tmp"
      if [ -f "$out" ] && diff -q "$out" "$tmp" > /dev/null 2>&1; then
        log "ok (in sync): $out"
      else
        log "DRIFT: $out is out of date — run scripts/compile-themes.sh"
        diff "$out" "$tmp" >&2 || true
        rc=1
      fi
      rm -f "$tmp"
    else
      compile_one "$json" > "$out"
      log "compiled: $out"
    fi
  done

  return $rc
}

main() {
  require_jq

  local target=""
  case "${1:-}" in
    --check) CHECK_MODE=true ;;
    "") ;;
    *) target="$1" ;;
  esac

  local rc=0
  if [ -n "$target" ]; then
    compile_theme_dir "$target" || rc=$?
  else
    local dir
    for dir in "$THEMES_ROOT"/*/; do
      [ -d "$dir" ] || continue
      compile_theme_dir "${dir%/}" || rc=$?
    done
  fi

  return $rc
}

main "$@"
